#!/bin/sh

mkdir -p ~/Games
mv ~/Загрузки/RaptorCalloftheShadows.tar.gz ~/Games
cd ~/Games
tar xvfz RaptorCalloftheShadows.tar.gz
rm RaptorCalloftheShadows.tar.gz
sudo rm /usr/share/applications/raptor-call-shadows-unarh.desktop
sudo mv /usr/share/raptor-call-shadows/raptor-call-shadows.desktop /usr/share/applications