#!/bin/sh

mkdir -p ~/Games
mv ~/Загрузки/AliensVersusPredatorGold.tar.gz ~/Games
cd ~/Games
tar xvfz AliensVersusPredatorGold.tar.gz
rm AliensVersusPredatorGold.tar.gz
sudo rm /usr/share/applications/aliens-versus-predator-gold-unarh.desktop
sudo mv /usr/share/aliens-versus-predator-gold/aliens-versus-predator-gold.desktop /usr/share/applications
