#!/bin/sh

mkdir -p ~/Games
mv ~/Загрузки/RedneckRampage.tar.gz ~/Games
cd ~/Games
tar xvfz RedneckRampage.tar.gz
rm RedneckRampage.tar.gz
sudo rm /usr/share/applications/redneck-rampage-unarh.desktop
sudo mv /usr/share/redneck-rampage/redneck-rampage.desktop /usr/share/applications