#!/bin/sh

mkdir -p ~/Games
mv ~/Загрузки/RedneckRampageRoute66.tar.gz ~/Games
cd ~/Games
tar xvfz RedneckRampageRoute66.tar.gz
rm RedneckRampageRoute66.tar.gz
sudo rm /usr/share/applications/redneck-rampage-route66-unarh.desktop
sudo mv /usr/share/redneck-rampage/redneck-rampage-route66.desktop /usr/share/applications
