#!/bin/sh

mkdir -p ~/Games
mv ~/Загрузки/AmericasArmySpecialForces.tar.gz ~/Games
cd ~/Games
tar xvfz AmericasArmySpecialForces.tar.gz
rm AmericasArmySpecialForces.tar.gz
sudo rm /usr/share/applications/americas-army-special-forces-unarh.desktop
sudo mv /usr/share/americas-army-special-forces/americas-army-special-forces.desktop /usr/share/applications
