#!/bin/sh

mkdir -p ~/Games
mv ~/Загрузки/JazzJackRabbit.tar.gz ~/Games
cd ~/Games
tar xvfz JazzJackRabbit.tar.gz
rm JazzJackRabbit.tar.gz
sudo rm /usr/share/applications/jazz-jack-rabbit-unarh.desktop
sudo mv /usr/share/jazz-jack-rabbit/jazz-jack-rabbit.desktop /usr/share/applications/